# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: MicrosoftCorporation.Microsoft.NETCoreRuntime-2.1.30(x64)
PackageVersion: 2.1.30.30411
PackageLocale: de
Publisher: Microsoft Corporation
PackageName: Microsoft .NET Core Runtime - 2.1.30 (x64)
License: MIT
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
ShortDescription: Microsoft .NET Core Runtime - 2.1.30 (x64)
ManifestType: defaultLocale
ManifestVersion: 1.6.0
